[package]
name = "mpirs"
version = "0.1.0"
authors = ["Sushant <sushant.dinesh94@gmail.com>",
           "Karthik Senthil <karthik.senthil@gmail.com>"]

[[bin]]
name = "mpirun"
path = "mpirun/main.rs"

[dependencies]
docopt = "0.6"
rustc-serialize = "*"
libc = "*"
